#!/usr/bin/env bash
#
# Manages syncing between remote and local copies of the system-configs
# tracking a new system configuration file
#
# For more details, see https://docs.qcr.ai/reference/resources/config_tracking_tool/


#################
### VARIABLES ###
#################


# The name of this script, and the directory where it is located
SCRIPT_NAME="$(basename $(readlink -f $0))"
SCRIPT_DIR="$(dirname $(readlink -f $0))"

# User config directory and files
UC_DIR=$(dirname ${SCRIPT_DIR})/.user_config
DEFAULTS_FILE=${UC_DIR}/defaults
ENC_TOKEN_FILE=${UC_DIR}/enc_token

# Variables
PULL=1
GH_TOKEN=""
GH_REPO=""
GH_PATH=""
GH_BRANCH=""

#################
### FUNCTIONS ###
#################

function print_usage(){
    printf "\nSyncs a set of tracked files with a remote repository.
    
Usage:
    system_configs [-h|--help] sync <github_user_email>

"

}


function _check_local() {
  # Checks to see if a directory is a git repository
  if [ ! -e "$1/.git" ]; then
    echo 1
    return
  fi
  echo 0
}

function _check_remote() {
    STATUS=$(curl -I -s \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GH_TOKEN" \
        https://api.github.com/repos/$1 | head -n 1|cut -d$' ' -f2)
    
    if [ "$STATUS" == "200" ]; then
        echo 1
    else
        echo 0
    fi
}

function _create_remote() {
  # Create remote github repository
    curl -s -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GH_TOKEN" \
        -d "{\"name\":\"$2\",\"description\":\"System configuration files for $2\", \"private\": true,\"auto_init\": false, \"has_issues\": true,\"has_projects\": true,\"has_wiki\":true}" \
        "https://api.github.com/orgs/$1/repos"
}

function _create_local() {
  # Arguments: <LOCAL_REPO_PATH> <GH_OWNER> <GH_REPO> <BRANCH>

  # Navigate to local repo and init
  pushd $1 >/dev/null
  git init

  # Configure git
  git config --local init.defaultBranch $4
  git config --local user.name qcrbot
  git config --local user.email "qcrbot@qut.edu.au"

  # Create, and commit readme
  echo "# $3" > README.md
  git add README.md
  git commit -m "Initial commit from QCR system-configs tool"
  git branch -M $4
  git remote add origin git@github.com:$2/$3.git
  git push -u origin $4
  popd >/dev/null
}

function _check_required_variables() {
  # Check GH_EMAIL is set
  if [ -z $GH_EMAIL ]; then
    printf "${ERROR}You must supply your GitHub user email to sync files.\n"
    exit 1
  fi

  # Check GH_OWNER is set
  if [ "${GH_OWNER}" == "" ]; then
    if [ -z ${UC_GH_OWNER} ]; then
      printf "${ERROR}You must set the default GitHub User via 'system-configs config --owner <user>' or by providing it using the '--owner' argument.\n"
      exit 1
    fi
    GH_OWNER=${UC_GH_OWNER}
  fi

  # Check TOKEN is set
  if [ "${GH_TOKEN}" == "" ]; then
    if [ ! -e ${ENC_TOKEN_FILE} ]; then
      printf "${ERROR}You must set the default GitHub PAT (token) via 'system-configs config --pat <token>' or by providing it using the '--token' argument.\n"
      exit 1
    fi
    # Decrypt token
    GH_TOKEN=$(gpg --decrypt ${ENC_TOKEN_FILE})
  fi

  # Check GH_BRANCH is set
  if [ "$GH_BRANCH" == "" ]; then
    GH_BRANCH=$GH_DEFAULT_BRANCH
  fi
}


###################
### MAIN SCRIPT ###
###################

# Source common
source ${SCRIPT_DIR}/common

# Source user config
if [ -e ${DEFAULTS_FILE} ]; then
  source ${DEFAULTS_FILE}
fi

# Parse Arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help) 
      print_usage
      exit 0;;
    -H|--host|--hostname)
      HOSTNAME="$2"
      shift 2
      ;;
    -b|--branch)
      GH_BRANCH="$2"
      shift 2
      ;;
    -sp|--store-path)
      STORE_PATH="$2"
      shift 2
      ;;
    -c|--create-remote)
      CREATE_REMOTE=0
      shift
      ;;
    -o|--owner)
      GH_OWNER="$2"
      shift 2
      ;;
    -np|--no-pull)
      PULL=1
      shift
      ;;
    -p|--pat)
      GH_TOKEN="$2"
      shift 2
      ;;
    -t|--template)
      TEMPLATE="$2"
      shift 2
      ;;
    *)
      if [ -z "$GH_EMAIL" ]; then
        GH_EMAIL="$1"
        shift
      else
        echo "Invalid argument: \"$1\""
        exit 1
      fi
  esac
done


# Make sure top level directories exist
# and have correct ownership
_create_directory_and_set_ownership $STORE_PATH
_create_directory_and_set_ownership $BACK_UP_PATH

# Check required variables are set
# Either from command line or user config
_check_required_variables

# Set repo name
HOSTNAME=$(_get_base_name $HOSTNAME)
if [ -z $TEMPLATE ]; then
  GH_REPO="system-configs-$HOSTNAME"
else
  GH_REPO="template-$TEMPLATE"
fi


# Set github path and local repo root path (root)
GH_PATH="$GH_OWNER/$GH_REPO"
LOCAL_ROOT=$STORE_PATH/$GH_REPO

# Make sure local root exists
mkdir -p $LOCAL_ROOT

# Print information to user
printf "\n${INFO}Hostname: $HOSTNAME\n"
printf "${INFO}GitHub Email: $GH_EMAIL\n"
printf "${INFO}GitHub Owner: $GH_OWNER\n"
printf "${INFO}GitHub Repo: $GH_REPO\n"
printf "${INFO}GitHub Branch: $GH_BRANCH\n"
printf "${INFO}Local Repo Path: $LOCAL_ROOT\n"
printf "${INFO}Remote Repository: https://github.com/$GH_PATH\n\n"

# Create remote if it doesn't exist
if [ "$(_check_remote $GH_PATH)" == "0" ]; then
    if [ "$CREATE_REMOTE" == "1" ] || [ "$(_prompt 'Remote does not exist. Create it?')" == "1" ]; then
        printf "${INFO}Attempting to create remote...\n"
        printf "\t- Owner: ${GH_OWNER}\n"
        printf "\t- Repo: ${GH_REPO}\n"
        _create_remote $GH_OWNER $GH_REPO
    else
        printf "${INFO}Unable to continue, nothing to do...\n"
        exit 0
    fi
fi

# Create/init local repo if required
if [ "$(_check_local $LOCAL_ROOT)" == "1" ]; then
    printf "\n${INFO}Initialising local repo...\n"
    _create_local $LOCAL_ROOT $GH_OWNER $GH_REPO $GH_DEFAULT_BRANCH
fi

# Pull down latest
if [ "$PULL" == "1" ]; then
    # TODO: Deal with local changes, merge conflicts, etc.
    printf "\n${INFO}Pulling from remote...\n"
    git pull
fi


# Update template using system configuration
if [ ! -z $TEMPLATE ]; then

  # Get configuration files
  CONFIG_ROOT=$STORE_PATH/"system-configs-$HOSTNAME"
  FILES=$(find ${CONFIG_ROOT} -type f -not -path "*.git*" -not -name "README.md")

  # Add any missing files to template
  printf "\n${INFO}Adding files to template...\n"
  DIFF_FILES=()
  for f in ${FILES[@]}; do
    # Get file path without CONFIG_ROOT
    f="${f//$CONFIG_ROOT}"

    # See if already exists in template
    if [ ! -e ${LOCAL_ROOT}/$f ]; then
      printf "\t-$f\n"
      mkdir -p $(dirname $LOCAL_ROOT/$f)
      rsync $CONFIG_ROOT/$f $LOCAL_ROOT/$f
    elif ! cmp -s "$CONFIG_ROOT/$f" "$LOCAL_ROOT/$f"; then
      DIFF_FILES+=("$f")
    fi
  done
  echo ""

  # Report any differences if files already exist
  if [[ ${#DIFF_FILES} -gt 0 ]]; then
    printf "${WARN}Differences between the system configuration and template were found in...\n"
    for f in ${DIFF_FILES[@]}; do
      printf "\t- Difference in $f\n"
    done
    printf "${WARN}You will need to manually update the template files to create the required changes.\n"
  else
    printf "${INFO}No differences found between the system configuration and the template\n"
  fi
fi

# Navigate to local repo, set user email
# GitHub uses user email to show committer not GitHub username
pushd $LOCAL_ROOT >/dev/null
git config user.email $GH_EMAIL

# Move to desired branch
printf "\n${INFO}Checking out branch ${GH_BRANCH}...\n"
git checkout $GH_BRANCH 2>/dev/null
if [ "$?" != "0" ]; then
    git branch $GH_BRANCH
    git checkout $GH_BRANCH
fi

# Add and commit
printf "\n${INFO}Adding and committing files...\n"
git add .
git commit -m 'Commit made by QCR system-config tools'

# Check if remote branch exists, and push to branch
printf "\n${INFO}Pushing local to remote...\n"
EXISTS=$(git branch -l -a | grep "remotes/origin/$GH_BRANCH")
if [ "$EXISTS" == "" ]; then
    git push --set-upstream origin $GH_BRANCH
else
    git push
fi

# Move back to original directory
popd

